name: Deploy Remix App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }} # typically 'root' or your username
          password: ${{ secrets.SSH_PASSWORD }}
          port: 6251
          script: |
            cd /var/www/iiuc-web-remix
            git pull origin main
            npm install --omit=dev
            pm2 restart ${{ secrets.PM2_APP_NAME }} || pm2 start server.js --name ${{ secrets.PM2_APP_NAME }}
            pm2 save
