name: Deploy Remix App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          port: 6251
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/iiuc-web-remix
            git pull origin main
            npm install --omit=dev
            pm2 restart ${{ secrets.PM2_APP_NAME }} || pm2 start server.js --name ${{ secrets.PM2_APP_NAME }}
            pm2 save
